import canada from "@/assets/icons/canada.png";
import southKorea from "@/assets/icons/south-korea.png";
import vietnam from "@/assets/icons/vietnam.png";

export const monthsArray = [
  { label: "January", value: "1" },
  { label: "February", value: "2" },
  { label: "March", value: "3" },
  { label: "April", value: "4" },
  { label: "May", value: "5" },
  { label: "June", value: "6" },
  { label: "July", value: "7" },
  { label: "August", value: "8" },
  { label: "September", value: "9" },
  { label: "October", value: "10" },
  { label: "November", value: "11" },
  { label: "December", value: "12" },
];

export const currencyList = [
  { label: "USD - United States Dollar", value: "USD" },
  { label: "EUR - Euro", value: "EUR" },
  { label: "JPY - Japanese Yen", value: "JPY" },
  { label: "GBP - British Pound Sterling", value: "GBP" },
  { label: "AUD - Australian Dollar", value: "AUD" },
  { label: "CAD - Canadian Dollar", value: "CAD" },
  { label: "CHF - Swiss Franc", value: "CHF" },
  { label: "CNY - Chinese Yuan Renminbi", value: "CNY" },
  { label: "SEK - Swedish Krona", value: "SEK" },
  { label: "NZD - New Zealand Dollar", value: "NZD" },
  { label: "MXN - Mexican Peso", value: "MXN" },
  { label: "SGD - Singapore Dollar", value: "SGD" },
  { label: "HKD - Hong Kong Dollar", value: "HKD" },
  { label: "NOK - Norwegian Krone", value: "NOK" },
  { label: "KRW - South Korean Won", value: "KRW" },
  { label: "TRY - Turkish Lira", value: "TRY" },
  { label: "RUB - Russian Ruble", value: "RUB" },
  { label: "INR - Indian Rupee", value: "INR" },
  { label: "BRL - Brazilian Real", value: "BRL" },
  { label: "ZAR - South African Rand", value: "ZAR" },
  { label: "DKK - Danish Krone", value: "DKK" },
  { label: "PLN - Polish Złoty", value: "PLN" },
  { label: "HUF - Hungarian Forint", value: "HUF" },
  { label: "CZK - Czech Koruna", value: "CZK" },
  { label: "ILS - Israeli New Shekel", value: "ILS" },
  { label: "CLP - Chilean Peso", value: "CLP" },
  { label: "IDR - Indonesian Rupiah", value: "IDR" },
  { label: "MYR - Malaysian Ringgit", value: "MYR" },
  { label: "PHP - Philippine Peso", value: "PHP" },
  { label: "THB - Thai Baht", value: "THB" },
  { label: "ARS - Argentine Peso", value: "ARS" },
  { label: "AED - UAE Dirham", value: "AED" },
  { label: "COP - Colombian Peso", value: "COP" },
  { label: "SAR - Saudi Riyal", value: "SAR" },
  { label: "VND - Vietnamese Dong", value: "VND" },
  { label: "KZT - Kazakhstani Tenge", value: "KZT" },
  { label: "QAR - Qatari Riyal", value: "QAR" },
  { label: "KWD - Kuwaiti Dinar", value: "KWD" },
  { label: "EGP - Egyptian Pound", value: "EGP" },
  { label: "UAH - Ukrainian Hryvnia", value: "UAH" },
  { label: "PEN - Peruvian Sol", value: "PEN" },
  { label: "NGN - Nigerian Naira", value: "NGN" },
  { label: "RON - Romanian Leu", value: "RON" },
  { label: "CZK - Czech Koruna", value: "CZK" },
  { label: "OMR - Omani Rial", value: "OMR" },
  { label: "BYN - Belarusian Ruble", value: "BYN" },
  { label: "BHD - Bahraini Dinar", value: "BHD" },
  { label: "JOD - Jordanian Dinar", value: "JOD" },
  { label: "CRC - Costa Rican Colón", value: "CRC" },
  { label: "GTQ - Guatemalan Quetzal", value: "GTQ" },
  { label: "PAB - Panamanian Balboa", value: "PAB" },
  { label: "UYU - Uruguayan Peso", value: "UYU" },
  { label: "PYG - Paraguayan Guarani", value: "PYG" },
  { label: "LKR - Sri Lankan Rupee", value: "LKR" },
  { label: "AZN - Azerbaijani Manat", value: "AZN" },
  { label: "TMT - Turkmenistani Manat", value: "TMT" },
  { label: "UZS - Uzbekistani Som", value: "UZS" },
  { label: "LBP - Lebanese Pound", value: "LBP" },
  { label: "BWP - Botswana Pula", value: "BWP" },
  { label: "ISK - Icelandic Króna", value: "ISK" },
  { label: "NPR - Nepalese Rupee", value: "NPR" },
  { label: "BND - Brunei Dollar", value: "BND" },
  { label: "AMD - Armenian Dram", value: "AMD" },
  { label: "KHR - Cambodian Riel", value: "KHR" },
  { label: "MMK - Myanmar Kyat", value: "MMK" },
  { label: "LAK - Laotian Kip", value: "LAK" },
  { label: "MVR - Maldivian Rufiyaa", value: "MVR" },
  { label: "ETB - Ethiopian Birr", value: "ETB" },
  { label: "RWF - Rwandan Franc", value: "RWF" },
  { label: "MUR - Mauritian Rupee", value: "MUR" },
  { label: "MGA - Malagasy Ariary", value: "MGA" },
  { label: "MWK - Malawian Kwacha", value: "MWK" },
  { label: "BIF - Burundian Franc", value: "BIF" },
  { label: "SCR - Seychellois Rupee", value: "SCR" },
  { label: "KMF - Comorian Franc", value: "KMF" },
  { label: "DJF - Djiboutian Franc", value: "DJF" },
  { label: "XCD - East Caribbean Dollar", value: "XCD" },
  { label: "TTD - Trinidad and Tobago Dollar", value: "TTD" },
  { label: "GYD - Guyanese Dollar", value: "GYD" },
  { label: "SRD - Surinamese Dollar", value: "SRD" },
  { label: "FJD - Fijian Dollar", value: "FJD" },
  { label: "PGK - Papua New Guinean Kina", value: "PGK" },
  { label: "SBD - Solomon Islands Dollar", value: "SBD" },
  { label: "VUV - Vanuatu Vatu", value: "VUV" },
  { label: "WST - Samoan Tala", value: "WST" },
  { label: "TOP - Tongan Paʻanga", value: "TOP" },
  { label: "KID - Kiribati Dollar", value: "KID" },
  { label: "TVD - Tuvaluan Dollar", value: "TVD" },
  { label: "XAF - Central African CFA Franc", value: "XAF" },
  { label: "XOF - West African CFA Franc", value: "XOF" },
  { label: "XPF - CFP Franc", value: "XPF" },
  { label: "DJF - Djiboutian Franc", value: "DJF" },
  { label: "ERN - Eritrean Nakfa", value: "ERN" },
  { label: "SZL - Swazi Lilangeni", value: "SZL" },
  { label: "LSL - Lesotho Loti", value: "LSL" },
  { label: "NAD - Namibian Dollar", value: "NAD" },
  { label: "ZMW - Namibian Dollar", value: "ZMW" },
  { label: "AOA - Angolan Kwanza", value: "AOA" },
  { label: "MZN - Mozambican Metical", value: "MZN" },
  { label: "BWP - Botswana Pula", value: "BWP" },
];

export const countryList = [
  { label: "Vietnam", value: 1 },
  { label: "Korea", value: 2 },
  { label: "Canada", value: 3 },
];

export const countryPhoneList = [
  { label: "Vietnam (+84)", icon: vietnam, value: "vietnam" },
  { label: "Korea (+82)", icon: southKorea, value: "korea" },
  { label: "Canada (+1)", icon: canada, value: "canada" },
];

export const categoriesList = [
  { label: "Onboarding and Benefits", value: "1" },
  { label: "Job Posting", value: "2" },
  { label: "Communication", value: "3" },
  { label: "Technology and Tools", value: "4" },
  { label: "Policies", value: "5" },
];

export const timezoneOptions = [
  { value: "-12", label: "UTC-12:00" },
  { value: "-11", label: "UTC-11:00" },
  { value: "-10", label: "UTC-10:00" },
  { value: "-9", label: "UTC-09:00" },
  { value: "-8", label: "UTC-08:00" },
  { value: "-7", label: "UTC-07:00" },
  { value: "-6", label: "UTC-06:00" },
  { value: "-5", label: "UTC-05:00" },
  { value: "-4", label: "UTC-04:00" },
  { value: "-3", label: "UTC-03:00" },
  { value: "-2", label: "UTC-02:00" },
  { value: "-1", label: "UTC-01:00" },
  { value: "0", label: "UTC±00:00" },
  { value: "1", label: "UTC+01:00" },
  { value: "2", label: "UTC+02:00" },
  { value: "3", label: "UTC+03:00" },
  { value: "4", label: "UTC+04:00" },
  { value: "5", label: "UTC+05:00" },
  { value: "6", label: "UTC+06:00" },
  { value: "7", label: "UTC+07:00" },
  { value: "8", label: "UTC+08:00" },
  { value: "9", label: "UTC+09:00" },
  { value: "10", label: "UTC+10:00" },
  { value: "11", label: "UTC+11:00" },
  { value: "12", label: "UTC+12:00" },
  { value: "13", label: "UTC+13:00" },
  { value: "14", label: "UTC+14:00" },
];
